### ISSUE TITLE
"Your license key is invalid."

### ISSUE THREAD

**Issue by soderlind** [mt-support/tribe-ext-extension-template#23]
I've [started on an extension](https://github.com/soderlind/event-attendee-notifications) using the template. I've changed the extension template variables manually (where's your slack?). On the plugin page I get "Your license key is invalid." Why?

<img width="789" alt="Utvidelser ‹ Kalender — WordPress 2021-03-18 10-44-10" src="https://user-images.githubusercontent.com/1649452/111609006-23500880-87da-11eb-97c2-0248dbf17ae8.png">

I do the development on a local multisite server, domain tld is `.local`. I have the multisite lisence for Event Calendar Pro and Event Ticket Plus.

**Comment by andrasguseo** [comment]
Hi @soderlind 
Thanks for reporting that,
We did some tweaks and updated the template so that should not happen anymore if you use that.
